package com.example.kidsgames.feature.jigsaw

import com.example.kidsgames.core.Word

/**
 * A large trilingual picture vocabulary (English / Polish / Portuguese-BR), each with an
 * emoji that is rendered into a puzzle picture. Adding a word here adds a puzzle, a
 * Find-It option and a spoken flashcard automatically. Kept common/child-friendly.
 *
 * Translations are best-effort common nouns — feel free to correct any.
 */
internal val VOCAB: List<Word> = listOf(
    // --- Animals ---
    Word("dog", "pies", "cachorro", "🐶"),
    Word("cat", "kot", "gato", "🐱"),
    Word("mouse", "mysz", "rato", "🐭"),
    Word("hamster", "chomik", "hamster", "🐹"),
    Word("rabbit", "królik", "coelho", "🐰"),
    Word("fox", "lis", "raposa", "🦊"),
    Word("bear", "niedźwiedź", "urso", "🐻"),
    Word("panda", "panda", "panda", "🐼"),
    Word("koala", "koala", "coala", "🐨"),
    Word("tiger", "tygrys", "tigre", "🐯"),
    Word("lion", "lew", "leão", "🦁"),
    Word("cow", "krowa", "vaca", "🐮"),
    Word("pig", "świnia", "porco", "🐷"),
    Word("frog", "żaba", "sapo", "🐸"),
    Word("monkey", "małpa", "macaco", "🐵"),
    Word("chicken", "kurczak", "galinha", "🐔"),
    Word("penguin", "pingwin", "pinguim", "🐧"),
    Word("bird", "ptak", "pássaro", "🐦"),
    Word("duck", "kaczka", "pato", "🦆"),
    Word("eagle", "orzeł", "águia", "🦅"),
    Word("owl", "sowa", "coruja", "🦉"),
    Word("wolf", "wilk", "lobo", "🐺"),
    Word("horse", "koń", "cavalo", "🐴"),
    Word("unicorn", "jednorożec", "unicórnio", "🦄"),
    Word("bee", "pszczoła", "abelha", "🐝"),
    Word("butterfly", "motyl", "borboleta", "🦋"),
    Word("snail", "ślimak", "caracol", "🐌"),
    Word("ladybug", "biedronka", "joaninha", "🐞"),
    Word("ant", "mrówka", "formiga", "🐜"),
    Word("spider", "pająk", "aranha", "🕷️"),
    Word("turtle", "żółw", "tartaruga", "🐢"),
    Word("snake", "wąż", "cobra", "🐍"),
    Word("lizard", "jaszczurka", "lagarto", "🦎"),
    Word("octopus", "ośmiornica", "polvo", "🐙"),
    Word("crab", "krab", "caranguejo", "🦀"),
    Word("fish", "ryba", "peixe", "🐟"),
    Word("dolphin", "delfin", "golfinho", "🐬"),
    Word("whale", "wieloryb", "baleia", "🐳"),
    Word("shark", "rekin", "tubarão", "🦈"),
    Word("crocodile", "krokodyl", "crocodilo", "🐊"),
    Word("elephant", "słoń", "elefante", "🐘"),
    Word("rhino", "nosorożec", "rinoceronte", "🦏"),
    Word("hippo", "hipopotam", "hipopótamo", "🦛"),
    Word("giraffe", "żyrafa", "girafa", "🦒"),
    Word("zebra", "zebra", "zebra", "🦓"),
    Word("deer", "jeleń", "veado", "🦌"),
    Word("sheep", "owca", "ovelha", "🐑"),
    Word("goat", "koza", "cabra", "🐐"),
    Word("camel", "wielbłąd", "camelo", "🐪"),
    Word("kangaroo", "kangur", "canguru", "🦘"),
    Word("hedgehog", "jeż", "ouriço", "🦔"),
    Word("squirrel", "wiewiórka", "esquilo", "🐿️"),
    Word("parrot", "papuga", "papagaio", "🦜"),
    Word("swan", "łabędź", "cisne", "🦢"),
    Word("rooster", "kogut", "galo", "🐓"),
    Word("chick", "pisklę", "pintinho", "🐣"),

    // --- Body parts ---
    Word("eye", "oko", "olho", "👁️"),
    Word("ear", "ucho", "orelha", "👂"),
    Word("nose", "nos", "nariz", "👃"),
    Word("mouth", "usta", "boca", "👄"),
    Word("tongue", "język", "língua", "👅"),
    Word("tooth", "ząb", "dente", "🦷"),
    Word("hand", "ręka", "mão", "🖐️"),
    Word("foot", "stopa", "pé", "🦶"),
    Word("leg", "noga", "perna", "🦵"),
    Word("arm", "ramię", "braço", "💪"),
    Word("brain", "mózg", "cérebro", "🧠"),
    Word("heart", "serce", "coração", "❤️"),
    Word("bone", "kość", "osso", "🦴"),

    // --- Food ---
    Word("apple", "jabłko", "maçã", "🍎"),
    Word("pear", "gruszka", "pera", "🍐"),
    Word("orange", "pomarańcza", "laranja", "🍊"),
    Word("lemon", "cytryna", "limão", "🍋"),
    Word("banana", "banan", "banana", "🍌"),
    Word("watermelon", "arbuz", "melancia", "🍉"),
    Word("grapes", "winogrona", "uvas", "🍇"),
    Word("strawberry", "truskawka", "morango", "🍓"),
    Word("cherry", "wiśnia", "cereja", "🍒"),
    Word("peach", "brzoskwinia", "pêssego", "🍑"),
    Word("mango", "mango", "manga", "🥭"),
    Word("pineapple", "ananas", "abacaxi", "🍍"),
    Word("coconut", "kokos", "coco", "🥥"),
    Word("tomato", "pomidor", "tomate", "🍅"),
    Word("carrot", "marchewka", "cenoura", "🥕"),
    Word("corn", "kukurydza", "milho", "🌽"),
    Word("potato", "ziemniak", "batata", "🥔"),
    Word("bread", "chleb", "pão", "🍞"),
    Word("cheese", "ser", "queijo", "🧀"),
    Word("egg", "jajko", "ovo", "🥚"),
    Word("hamburger", "hamburger", "hambúrguer", "🍔"),
    Word("fries", "frytki", "batata frita", "🍟"),
    Word("pizza", "pizza", "pizza", "🍕"),
    Word("sandwich", "kanapka", "sanduíche", "🥪"),
    Word("ice cream", "lody", "sorvete", "🍦"),
    Word("donut", "pączek", "rosquinha", "🍩"),
    Word("cookie", "ciastko", "biscoito", "🍪"),
    Word("cake", "tort", "bolo", "🎂"),
    Word("chocolate", "czekolada", "chocolate", "🍫"),
    Word("candy", "cukierek", "bala", "🍬"),
    Word("lollipop", "lizak", "pirulito", "🍭"),
    Word("honey", "miód", "mel", "🍯"),
    Word("milk", "mleko", "leite", "🥛"),
    Word("juice", "sok", "suco", "🧃"),
    Word("popcorn", "popcorn", "pipoca", "🍿"),

    // --- Objects & home ---
    Word("ball", "piłka", "bola", "⚽"),
    Word("balloon", "balon", "balão", "🎈"),
    Word("gift", "prezent", "presente", "🎁"),
    Word("teddy bear", "miś", "ursinho", "🧸"),
    Word("book", "książka", "livro", "📚"),
    Word("pencil", "ołówek", "lápis", "✏️"),
    Word("key", "klucz", "chave", "🔑"),
    Word("clock", "zegar", "relógio", "🕰️"),
    Word("phone", "telefon", "telefone", "📱"),
    Word("camera", "aparat", "câmera", "📷"),
    Word("drum", "bęben", "tambor", "🥁"),
    Word("guitar", "gitara", "violão", "🎸"),
    Word("piano", "pianino", "piano", "🎹"),
    Word("kite", "latawiec", "pipa", "🪁"),
    Word("crown", "korona", "coroa", "👑"),
    Word("hat", "kapelusz", "chapéu", "🎩"),
    Word("cap", "czapka", "boné", "🧢"),
    Word("shirt", "koszulka", "camiseta", "👕"),
    Word("dress", "sukienka", "vestido", "👗"),
    Word("shoe", "but", "sapato", "👟"),
    Word("socks", "skarpetki", "meias", "🧦"),
    Word("gloves", "rękawiczki", "luvas", "🧤"),
    Word("scarf", "szalik", "cachecol", "🧣"),
    Word("glasses", "okulary", "óculos", "👓"),
    Word("umbrella", "parasol", "guarda-chuva", "🌂"),
    Word("bed", "łóżko", "cama", "🛏️"),
    Word("chair", "krzesło", "cadeira", "🪑"),
    Word("door", "drzwi", "porta", "🚪"),
    Word("soap", "mydło", "sabonete", "🧼"),
    Word("broom", "miotła", "vassoura", "🧹"),

    // --- Vehicles ---
    Word("car", "samochód", "carro", "🚗"),
    Word("bus", "autobus", "ônibus", "🚌"),
    Word("ambulance", "karetka", "ambulância", "🚑"),
    Word("fire truck", "wóz strażacki", "caminhão de bombeiros", "🚒"),
    Word("police car", "radiowóz", "carro de polícia", "🚓"),
    Word("tractor", "traktor", "trator", "🚜"),
    Word("bicycle", "rower", "bicicleta", "🚲"),
    Word("motorcycle", "motocykl", "moto", "🏍️"),
    Word("train", "pociąg", "trem", "🚂"),
    Word("helicopter", "helikopter", "helicóptero", "🚁"),
    Word("airplane", "samolot", "avião", "✈️"),
    Word("rocket", "rakieta", "foguete", "🚀"),
    Word("sailboat", "żaglówka", "veleiro", "⛵"),
    Word("ship", "statek", "navio", "🚢"),
    Word("truck", "ciężarówka", "caminhão", "🚚"),

    // --- Nature & weather ---
    Word("sun", "słońce", "sol", "☀️"),
    Word("moon", "księżyc", "lua", "🌙"),
    Word("star", "gwiazda", "estrela", "⭐"),
    Word("cloud", "chmura", "nuvem", "☁️"),
    Word("rain", "deszcz", "chuva", "🌧️"),
    Word("snow", "śnieg", "neve", "❄️"),
    Word("snowman", "bałwan", "boneco de neve", "⛄"),
    Word("rainbow", "tęcza", "arco-íris", "🌈"),
    Word("fire", "ogień", "fogo", "🔥"),
    Word("water", "woda", "água", "💧"),
    Word("wave", "fala", "onda", "🌊"),
    Word("flower", "kwiat", "flor", "🌸"),
    Word("sunflower", "słonecznik", "girassol", "🌻"),
    Word("cactus", "kaktus", "cacto", "🌵"),
    Word("tree", "drzewo", "árvore", "🌳"),
    Word("mushroom", "grzyb", "cogumelo", "🍄"),
    Word("leaf", "liść", "folha", "🍁"),
    Word("earth", "ziemia", "terra", "🌍"),
    Word("mountain", "góra", "montanha", "🏔️"),

    // --- More animals ---
    Word("gorilla", "goryl", "gorila", "🦍"),
    Word("sloth", "leniwiec", "preguiça", "🦥"),
    Word("otter", "wydra", "lontra", "🦦"),
    Word("raccoon", "szop", "guaxinim", "🦝"),
    Word("llama", "lama", "lhama", "🦙"),
    Word("flamingo", "flaming", "flamingo", "🦩"),
    Word("dove", "gołąb", "pomba", "🕊️"),
    Word("peacock", "paw", "pavão", "🦚"),
    Word("dragon", "smok", "dragão", "🐉"),
    Word("bat", "nietoperz", "morcego", "🦇"),
    Word("seal", "foka", "foca", "🦭"),
    Word("caterpillar", "gąsienica", "lagarta", "🐛"),
    Word("scorpion", "skorpion", "escorpião", "🦂"),
    Word("dinosaur", "dinozaur", "dinossauro", "🦕"),

    // --- More food ---
    Word("broccoli", "brokuł", "brócolis", "🥦"),
    Word("avocado", "awokado", "abacate", "🥑"),
    Word("cucumber", "ogórek", "pepino", "🥒"),
    Word("onion", "cebula", "cebola", "🧅"),
    Word("garlic", "czosnek", "alho", "🧄"),
    Word("croissant", "rogalik", "croissant", "🥐"),
    Word("pancakes", "naleśniki", "panquecas", "🥞"),
    Word("sushi", "sushi", "sushi", "🍣"),
    Word("rice", "ryż", "arroz", "🍚"),
    Word("spaghetti", "spaghetti", "espaguete", "🍝"),
    Word("salad", "sałatka", "salada", "🥗"),
    Word("cupcake", "babeczka", "cupcake", "🧁"),
    Word("taco", "taco", "taco", "🌮"),
    Word("peanut", "orzeszek", "amendoim", "🥜"),

    // --- More objects ---
    Word("scissors", "nożyczki", "tesoura", "✂️"),
    Word("hammer", "młotek", "martelo", "🔨"),
    Word("ruler", "linijka", "régua", "📏"),
    Word("crayon", "kredka", "giz de cera", "🖍️"),
    Word("backpack", "plecak", "mochila", "🎒"),
    Word("bell", "dzwonek", "sino", "🔔"),
    Word("candle", "świeca", "vela", "🕯️"),
    Word("bucket", "wiadro", "balde", "🪣"),
    Word("ladder", "drabina", "escada", "🪜"),
    Word("toothbrush", "szczoteczka", "escova de dentes", "🪥"),
    Word("mirror", "lustro", "espelho", "🪞"),
    Word("magnet", "magnes", "ímã", "🧲"),
    Word("alarm clock", "budzik", "despertador", "⏰"),
    Word("dice", "kostka", "dado", "🎲"),
    Word("trophy", "puchar", "troféu", "🏆"),
    Word("basketball", "koszykówka", "basquete", "🏀"),
    Word("baseball", "baseball", "beisebol", "⚾"),
    Word("saxophone", "saksofon", "saxofone", "🎷"),
    Word("trumpet", "trąbka", "trompete", "🎺"),

    // --- More vehicles ---
    Word("taxi", "taksówka", "táxi", "🚕"),
    Word("scooter", "hulajnoga", "patinete", "🛴"),
    Word("anchor", "kotwica", "âncora", "⚓"),

    // --- More nature ---
    Word("palm tree", "palma", "palmeira", "🌴"),
    Word("pine tree", "sosna", "pinheiro", "🌲"),
    Word("tulip", "tulipan", "tulipa", "🌷"),
    Word("rose", "róża", "rosa", "🌹"),
    Word("clover", "koniczyna", "trevo", "🍀"),
    Word("shell", "muszla", "concha", "🐚"),
    Word("volcano", "wulkan", "vulcão", "🌋"),
    Word("rock", "kamień", "pedra", "🪨"),

    // --- Even more animals ---
    Word("turkey", "indyk", "peru", "🦃"),
    Word("goose", "gęś", "ganso", "🪿"),
    Word("beaver", "bóbr", "castor", "🦫"),
    Word("badger", "borsuk", "texugo", "🦡"),
    Word("skunk", "skunks", "gambá", "🦨"),
    Word("ox", "wół", "boi", "🐂"),
    Word("ram", "baran", "carneiro", "🐏"),
    Word("mammoth", "mamut", "mamute", "🦣"),
    Word("moose", "łoś", "alce", "🫎"),
    Word("donkey", "osioł", "burro", "🫏"),
    Word("bison", "żubr", "bisão", "🦬"),
    Word("cricket", "świerszcz", "grilo", "🦗"),
    Word("fly", "mucha", "mosca", "🪰"),
    Word("beetle", "żuk", "besouro", "🪲"),
    Word("mosquito", "komar", "mosquito", "🦟"),
    Word("tropical fish", "rybka", "peixinho", "🐠"),
    Word("pufferfish", "rozdymka", "baiacu", "🐡"),
    Word("lobster", "homar", "lagosta", "🦞"),
    Word("shrimp", "krewetka", "camarão", "🦐"),
    Word("squid", "kałamarnica", "lula", "🦑"),
    Word("jellyfish", "meduza", "água-viva", "🪼"),

    // --- People ---
    Word("baby", "dziecko", "bebê", "👶"),
    Word("boy", "chłopiec", "menino", "👦"),
    Word("girl", "dziewczynka", "menina", "👧"),
    Word("man", "mężczyzna", "homem", "👨"),
    Word("woman", "kobieta", "mulher", "👩"),
    Word("grandpa", "dziadek", "vovô", "👴"),
    Word("grandma", "babcia", "vovó", "👵"),
    Word("police", "policjant", "policial", "👮"),
    Word("prince", "książę", "príncipe", "🤴"),
    Word("princess", "księżniczka", "princesa", "👸"),
    Word("wizard", "czarodziej", "mago", "🧙"),
    Word("fairy", "wróżka", "fada", "🧚"),
    Word("mermaid", "syrena", "sereia", "🧜"),
    Word("robot", "robot", "robô", "🤖"),
    Word("ghost", "duch", "fantasma", "👻"),
    Word("alien", "kosmita", "alienígena", "👽"),
    Word("Santa", "Mikołaj", "Papai Noel", "🎅"),
    Word("footprints", "ślady", "pegadas", "👣"),

    // --- More food & kitchen ---
    Word("eggplant", "bakłażan", "berinjela", "🍆"),
    Word("bell pepper", "papryka", "pimentão", "🫑"),
    Word("chili", "chili", "pimenta", "🌶️"),
    Word("lettuce", "sałata", "alface", "🥬"),
    Word("sweet potato", "batat", "batata-doce", "🍠"),
    Word("chestnut", "kasztan", "castanha", "🌰"),
    Word("baguette", "bagietka", "baguete", "🥖"),
    Word("bagel", "bajgiel", "bagel", "🥯"),
    Word("bacon", "boczek", "bacon", "🥓"),
    Word("meat", "mięso", "carne", "🍖"),
    Word("drumstick", "udko", "coxa", "🍗"),
    Word("hot dog", "hot dog", "cachorro-quente", "🌭"),
    Word("burrito", "burrito", "burrito", "🌯"),
    Word("fried egg", "jajko sadzone", "ovo frito", "🍳"),
    Word("waffle", "gofr", "waffle", "🧇"),
    Word("butter", "masło", "manteiga", "🧈"),
    Word("salt", "sól", "sal", "🧂"),
    Word("pudding", "budyń", "pudim", "🍮"),
    Word("pie", "placek", "torta", "🥧"),
    Word("tea", "herbata", "chá", "🍵"),
    Word("coffee", "kawa", "café", "☕"),
    Word("soda", "napój", "refrigerante", "🥤"),
    Word("blueberry", "jagoda", "mirtilo", "🫐"),
    Word("melon", "melon", "melão", "🍈"),
    Word("kiwi", "kiwi", "kiwi", "🥝"),
    Word("ice", "lód", "gelo", "🧊"),
    Word("plate", "talerz", "prato", "🍽️"),
    Word("spoon", "łyżka", "colher", "🥄"),
    Word("fork", "widelec", "garfo", "🍴"),
    Word("knife", "nóż", "faca", "🔪"),
    Word("bowl", "miska", "tigela", "🥣"),

    // --- Space, weather & nature ---
    Word("planet", "planeta", "planeta", "🪐"),
    Word("shooting star", "spadająca gwiazda", "estrela cadente", "🌠"),
    Word("comet", "kometa", "cometa", "☄️"),
    Word("lightning", "błyskawica", "relâmpago", "⚡"),
    Word("tornado", "tornado", "tornado", "🌪️"),
    Word("storm", "burza", "tempestade", "⛈️"),
    Word("fog", "mgła", "neblina", "🌫️"),
    Word("thermometer", "termometr", "termômetro", "🌡️"),
    Word("wind", "wiatr", "vento", "💨"),
    Word("bubbles", "bąbelki", "bolhas", "🫧"),
    Word("seedling", "sadzonka", "muda", "🌱"),
    Word("wheat", "pszenica", "trigo", "🌾"),
    Word("daisy", "stokrotka", "margarida", "🌼"),
    Word("bouquet", "bukiet", "buquê", "💐"),
    Word("island", "wyspa", "ilha", "🏝️"),
    Word("beach", "plaża", "praia", "🏖️"),
    Word("desert", "pustynia", "deserto", "🏜️"),
    Word("bridge", "most", "ponte", "🌉"),
    Word("satellite", "satelita", "satélite", "🛰️"),

    // --- Tools, home & science ---
    Word("laptop", "laptop", "notebook", "💻"),
    Word("computer", "komputer", "computador", "🖥️"),
    Word("watch", "zegarek", "relógio", "⌚"),
    Word("lock", "kłódka", "cadeado", "🔒"),
    Word("light bulb", "żarówka", "lâmpada", "💡"),
    Word("flashlight", "latarka", "lanterna", "🔦"),
    Word("fire extinguisher", "gaśnica", "extintor", "🧯"),
    Word("axe", "siekiera", "machado", "🪓"),
    Word("saw", "piła", "serra", "🪚"),
    Word("screwdriver", "śrubokręt", "chave de fenda", "🪛"),
    Word("bolt", "śruba", "parafuso", "🔩"),
    Word("gear", "koło zębate", "engrenagem", "⚙️"),
    Word("test tube", "probówka", "tubo de ensaio", "🧪"),
    Word("microscope", "mikroskop", "microscópio", "🔬"),
    Word("telescope", "teleskop", "telescópio", "🔭"),
    Word("pill", "tabletka", "comprimido", "💊"),
    Word("bandage", "plaster", "curativo", "🩹"),
    Word("toilet", "toaleta", "vaso sanitário", "🚽"),
    Word("shower", "prysznic", "chuveiro", "🚿"),
    Word("bathtub", "wanna", "banheira", "🛁"),
    Word("sponge", "gąbka", "esponja", "🧽"),
    Word("couch", "kanapa", "sofá", "🛋️"),
    Word("window", "okno", "janela", "🪟"),
    Word("picture", "obraz", "quadro", "🖼️"),
    Word("hourglass", "klepsydra", "ampulheta", "⏳"),
    Word("note", "notatka", "nota", "📝"),
    Word("paperclip", "spinacz", "clipe", "📎"),
    Word("pin", "pinezka", "alfinete", "📌"),
    Word("thread", "nić", "linha", "🧵"),
    Word("yarn", "włóczka", "lã", "🧶"),
    Word("bow", "kokarda", "laço", "🎀"),
    Word("bag", "torebka", "bolsa", "👜"),
    Word("ring", "pierścionek", "anel", "💍"),
    Word("coat", "płaszcz", "casaco", "🧥"),
    Word("jeans", "dżinsy", "calça", "👖"),
    Word("shorts", "szorty", "shorts", "🩳"),
    Word("tie", "krawat", "gravata", "👔"),
    Word("boot", "kozak", "bota", "👢"),
    Word("sunglasses", "okulary słoneczne", "óculos de sol", "🕶️"),

    // --- Toys, sports & music ---
    Word("tennis", "tenis", "tênis", "🎾"),
    Word("volleyball", "siatkówka", "vôlei", "🏐"),
    Word("ping pong", "ping-pong", "pingue-pongue", "🏓"),
    Word("badminton", "badminton", "badminton", "🏸"),
    Word("medal", "medal", "medalha", "🥇"),
    Word("target", "tarcza", "alvo", "🎯"),
    Word("puzzle", "puzzle", "quebra-cabeça", "🧩"),
    Word("yo-yo", "jo-jo", "ioiô", "🪀"),
    Word("controller", "kontroler", "controle", "🎮"),
    Word("violin", "skrzypce", "violino", "🎻"),
    Word("microphone", "mikrofon", "microfone", "🎤"),
    Word("headphones", "słuchawki", "fones", "🎧"),
    Word("music note", "nuta", "nota musical", "🎵"),
    Word("accordion", "akordeon", "acordeão", "🪗"),
    Word("circus", "cyrk", "circo", "🎪"),
    Word("carousel", "karuzela", "carrossel", "🎠"),
    Word("ferris wheel", "diabelski młyn", "roda-gigante", "🎡"),
    Word("roller coaster", "kolejka górska", "montanha-russa", "🎢"),
    Word("castle", "zamek", "castelo", "🏰"),
    Word("tent", "namiot", "barraca", "⛺"),

    // --- More transport & places ---
    Word("race car", "wyścigówka", "carro de corrida", "🏎️"),
    Word("skateboard", "deskorolka", "skate", "🛹"),
    Word("roller skate", "wrotki", "patins", "🛼"),
    Word("metro", "metro", "metrô", "🚇"),
    Word("tram", "tramwaj", "bonde", "🚊"),
    Word("UFO", "ufo", "óvni", "🛸"),
    Word("canoe", "kajak", "canoa", "🛶"),
    Word("speedboat", "motorówka", "lancha", "🚤"),
    Word("compass", "kompas", "bússola", "🧭"),
    Word("map", "mapa", "mapa", "🗺️"),
    Word("traffic light", "sygnalizacja", "semáforo", "🚦"),
    Word("hospital", "szpital", "hospital", "🏥"),
    Word("school", "szkoła", "escola", "🏫"),
    Word("house", "dom", "casa", "🏠"),
)
