package com.example.kidsgames.feature.jigsaw

import com.example.kidsgames.core.Word

/**
 * A large trilingual picture vocabulary (English / Polish / Portuguese-BR), each with an
 * emoji that is rendered into a puzzle picture. Adding a word here adds a puzzle, a
 * Find-It option and a spoken flashcard automatically. Kept common/child-friendly.
 *
 * Translations are best-effort common nouns — feel free to correct any.
 */
internal val VOCAB: List<Word> = listOf(
    // --- Animals ---
    Word("dog", "pies", "cachorro", "🐶"),
    Word("cat", "kot", "gato", "🐱"),
    Word("mouse", "mysz", "rato", "🐭"),
    Word("hamster", "chomik", "hamster", "🐹"),
    Word("rabbit", "królik", "coelho", "🐰"),
    Word("fox", "lis", "raposa", "🦊"),
    Word("bear", "niedźwiedź", "urso", "🐻"),
    Word("panda", "panda", "panda", "🐼"),
    Word("koala", "koala", "coala", "🐨"),
    Word("tiger", "tygrys", "tigre", "🐯"),
    Word("lion", "lew", "leão", "🦁"),
    Word("cow", "krowa", "vaca", "🐮"),
    Word("pig", "świnia", "porco", "🐷"),
    Word("frog", "żaba", "sapo", "🐸"),
    Word("monkey", "małpa", "macaco", "🐵"),
    Word("chicken", "kurczak", "galinha", "🐔"),
    Word("penguin", "pingwin", "pinguim", "🐧"),
    Word("bird", "ptak", "pássaro", "🐦"),
    Word("duck", "kaczka", "pato", "🦆"),
    Word("eagle", "orzeł", "águia", "🦅"),
    Word("owl", "sowa", "coruja", "🦉"),
    Word("wolf", "wilk", "lobo", "🐺"),
    Word("horse", "koń", "cavalo", "🐴"),
    Word("unicorn", "jednorożec", "unicórnio", "🦄"),
    Word("bee", "pszczoła", "abelha", "🐝"),
    Word("butterfly", "motyl", "borboleta", "🦋"),
    Word("snail", "ślimak", "caracol", "🐌"),
    Word("ladybug", "biedronka", "joaninha", "🐞"),
    Word("ant", "mrówka", "formiga", "🐜"),
    Word("spider", "pająk", "aranha", "🕷️"),
    Word("turtle", "żółw", "tartaruga", "🐢"),
    Word("snake", "wąż", "cobra", "🐍"),
    Word("lizard", "jaszczurka", "lagarto", "🦎"),
    Word("octopus", "ośmiornica", "polvo", "🐙"),
    Word("crab", "krab", "caranguejo", "🦀"),
    Word("fish", "ryba", "peixe", "🐟"),
    Word("dolphin", "delfin", "golfinho", "🐬"),
    Word("whale", "wieloryb", "baleia", "🐳"),
    Word("shark", "rekin", "tubarão", "🦈"),
    Word("crocodile", "krokodyl", "crocodilo", "🐊"),
    Word("elephant", "słoń", "elefante", "🐘"),
    Word("rhino", "nosorożec", "rinoceronte", "🦏"),
    Word("hippo", "hipopotam", "hipopótamo", "🦛"),
    Word("giraffe", "żyrafa", "girafa", "🦒"),
    Word("zebra", "zebra", "zebra", "🦓"),
    Word("deer", "jeleń", "veado", "🦌"),
    Word("sheep", "owca", "ovelha", "🐑"),
    Word("goat", "koza", "cabra", "🐐"),
    Word("camel", "wielbłąd", "camelo", "🐪"),
    Word("kangaroo", "kangur", "canguru", "🦘"),
    Word("hedgehog", "jeż", "ouriço", "🦔"),
    Word("squirrel", "wiewiórka", "esquilo", "🐿️"),
    Word("parrot", "papuga", "papagaio", "🦜"),
    Word("swan", "łabędź", "cisne", "🦢"),
    Word("rooster", "kogut", "galo", "🐓"),
    Word("chick", "pisklę", "pintinho", "🐣"),

    // --- Body parts ---
    Word("eye", "oko", "olho", "👁️"),
    Word("ear", "ucho", "orelha", "👂"),
    Word("nose", "nos", "nariz", "👃"),
    Word("mouth", "usta", "boca", "👄"),
    Word("tongue", "język", "língua", "👅"),
    Word("tooth", "ząb", "dente", "🦷"),
    Word("hand", "ręka", "mão", "🖐️"),
    Word("foot", "stopa", "pé", "🦶"),
    Word("leg", "noga", "perna", "🦵"),
    Word("arm", "ramię", "braço", "💪"),
    Word("brain", "mózg", "cérebro", "🧠"),
    Word("heart", "serce", "coração", "❤️"),
    Word("bone", "kość", "osso", "🦴"),

    // --- Food ---
    Word("apple", "jabłko", "maçã", "🍎"),
    Word("pear", "gruszka", "pera", "🍐"),
    Word("orange", "pomarańcza", "laranja", "🍊"),
    Word("lemon", "cytryna", "limão", "🍋"),
    Word("banana", "banan", "banana", "🍌"),
    Word("watermelon", "arbuz", "melancia", "🍉"),
    Word("grapes", "winogrona", "uvas", "🍇"),
    Word("strawberry", "truskawka", "morango", "🍓"),
    Word("cherry", "wiśnia", "cereja", "🍒"),
    Word("peach", "brzoskwinia", "pêssego", "🍑"),
    Word("mango", "mango", "manga", "🥭"),
    Word("pineapple", "ananas", "abacaxi", "🍍"),
    Word("coconut", "kokos", "coco", "🥥"),
    Word("tomato", "pomidor", "tomate", "🍅"),
    Word("carrot", "marchewka", "cenoura", "🥕"),
    Word("corn", "kukurydza", "milho", "🌽"),
    Word("potato", "ziemniak", "batata", "🥔"),
    Word("bread", "chleb", "pão", "🍞"),
    Word("cheese", "ser", "queijo", "🧀"),
    Word("egg", "jajko", "ovo", "🥚"),
    Word("hamburger", "hamburger", "hambúrguer", "🍔"),
    Word("fries", "frytki", "batata frita", "🍟"),
    Word("pizza", "pizza", "pizza", "🍕"),
    Word("sandwich", "kanapka", "sanduíche", "🥪"),
    Word("ice cream", "lody", "sorvete", "🍦"),
    Word("donut", "pączek", "rosquinha", "🍩"),
    Word("cookie", "ciastko", "biscoito", "🍪"),
    Word("cake", "tort", "bolo", "🎂"),
    Word("chocolate", "czekolada", "chocolate", "🍫"),
    Word("candy", "cukierek", "bala", "🍬"),
    Word("lollipop", "lizak", "pirulito", "🍭"),
    Word("honey", "miód", "mel", "🍯"),
    Word("milk", "mleko", "leite", "🥛"),
    Word("juice", "sok", "suco", "🧃"),
    Word("popcorn", "popcorn", "pipoca", "🍿"),

    // --- Objects & home ---
    Word("ball", "piłka", "bola", "⚽"),
    Word("balloon", "balon", "balão", "🎈"),
    Word("gift", "prezent", "presente", "🎁"),
    Word("teddy bear", "miś", "ursinho", "🧸"),
    Word("book", "książka", "livro", "📚"),
    Word("pencil", "ołówek", "lápis", "✏️"),
    Word("key", "klucz", "chave", "🔑"),
    Word("clock", "zegar", "relógio", "🕰️"),
    Word("phone", "telefon", "telefone", "📱"),
    Word("camera", "aparat", "câmera", "📷"),
    Word("drum", "bęben", "tambor", "🥁"),
    Word("guitar", "gitara", "violão", "🎸"),
    Word("piano", "pianino", "piano", "🎹"),
    Word("kite", "latawiec", "pipa", "🪁"),
    Word("crown", "korona", "coroa", "👑"),
    Word("hat", "kapelusz", "chapéu", "🎩"),
    Word("cap", "czapka", "boné", "🧢"),
    Word("shirt", "koszulka", "camiseta", "👕"),
    Word("dress", "sukienka", "vestido", "👗"),
    Word("shoe", "but", "sapato", "👟"),
    Word("socks", "skarpetki", "meias", "🧦"),
    Word("gloves", "rękawiczki", "luvas", "🧤"),
    Word("scarf", "szalik", "cachecol", "🧣"),
    Word("glasses", "okulary", "óculos", "👓"),
    Word("umbrella", "parasol", "guarda-chuva", "🌂"),
    Word("bed", "łóżko", "cama", "🛏️"),
    Word("chair", "krzesło", "cadeira", "🪑"),
    Word("door", "drzwi", "porta", "🚪"),
    Word("soap", "mydło", "sabonete", "🧼"),
    Word("broom", "miotła", "vassoura", "🧹"),

    // --- Vehicles ---
    Word("car", "samochód", "carro", "🚗"),
    Word("bus", "autobus", "ônibus", "🚌"),
    Word("ambulance", "karetka", "ambulância", "🚑"),
    Word("fire truck", "wóz strażacki", "caminhão de bombeiros", "🚒"),
    Word("police car", "radiowóz", "carro de polícia", "🚓"),
    Word("tractor", "traktor", "trator", "🚜"),
    Word("bicycle", "rower", "bicicleta", "🚲"),
    Word("motorcycle", "motocykl", "moto", "🏍️"),
    Word("train", "pociąg", "trem", "🚂"),
    Word("helicopter", "helikopter", "helicóptero", "🚁"),
    Word("airplane", "samolot", "avião", "✈️"),
    Word("rocket", "rakieta", "foguete", "🚀"),
    Word("sailboat", "żaglówka", "veleiro", "⛵"),
    Word("ship", "statek", "navio", "🚢"),
    Word("truck", "ciężarówka", "caminhão", "🚚"),

    // --- Nature & weather ---
    Word("sun", "słońce", "sol", "☀️"),
    Word("moon", "księżyc", "lua", "🌙"),
    Word("star", "gwiazda", "estrela", "⭐"),
    Word("cloud", "chmura", "nuvem", "☁️"),
    Word("rain", "deszcz", "chuva", "🌧️"),
    Word("snow", "śnieg", "neve", "❄️"),
    Word("snowman", "bałwan", "boneco de neve", "⛄"),
    Word("rainbow", "tęcza", "arco-íris", "🌈"),
    Word("fire", "ogień", "fogo", "🔥"),
    Word("water", "woda", "água", "💧"),
    Word("wave", "fala", "onda", "🌊"),
    Word("flower", "kwiat", "flor", "🌸"),
    Word("sunflower", "słonecznik", "girassol", "🌻"),
    Word("cactus", "kaktus", "cacto", "🌵"),
    Word("tree", "drzewo", "árvore", "🌳"),
    Word("mushroom", "grzyb", "cogumelo", "🍄"),
    Word("leaf", "liść", "folha", "🍁"),
    Word("earth", "ziemia", "terra", "🌍"),
    Word("mountain", "góra", "montanha", "🏔️"),
)
